2019-03-29 22:47:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.qiushibaike.com/text/page/13/> (referer: https://www.qiushibaike.com/text/page/12/)
Traceback (most recent call last):
  File "C:\Users\Victor\Anaconda3\envs\Scrapy\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "C:\Users\Victor\Anaconda3\envs\Scrapy\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "C:\Users\Victor\Anaconda3\envs\Scrapy\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Users\Victor\Anaconda3\envs\Scrapy\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\Victor\Anaconda3\envs\Scrapy\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "D:\Users\Victor\Documents\GitHub\Scrapy\qsbk\qsbk\spiders\qsbkzz.py", line 24, in parse
    next_url = response.xpath('//ul[@class="pagination"]/li[last()]/a/@href').extract()[0]
IndexError: list index out of range
